#!/bin/bash
# Example usage of culprit-finder
#
# This script demonstrates how to use culprit-finder to find
# a commit that broke tests in your repository.

set -e

echo "==================================================================="
echo "  Culprit Finder - Example Usage"
echo "==================================================================="
echo ""

# Build the tool
echo "▶ Building culprit-finder..."
go build -o culprit-finder
echo "✓ Build complete"
echo ""

# Example 1: Basic usage
echo "==================================================================="
echo "  Example 1: Basic Usage"
echo "==================================================================="
echo ""
echo "Find culprits between v1.0 and HEAD:"
echo ""
echo "  ./culprit-finder start v1.0 HEAD -- make test"
echo "  ./culprit-finder run"
echo "  ./culprit-finder status"
echo "  ./culprit-finder reset"
echo ""

# Example 2: Flaky tests
echo "==================================================================="
echo "  Example 2: Handling Flaky Tests"
echo "==================================================================="
echo ""
echo "For tests with ~15% flake rate:"
echo ""
echo "  ./culprit-finder start \\"
echo "    --repetitions 5 \\"
echo "    --flake-rate 0.15 \\"
echo "    main HEAD -- npm test"
echo ""
echo "  ./culprit-finder run --progress"
echo ""

# Example 3: Multiple culprits
echo "==================================================================="
echo "  Example 3: Finding Multiple Culprits"
echo "==================================================================="
echo ""
echo "When you suspect multiple breaking commits:"
echo ""
echo "  ./culprit-finder start \\"
echo "    --max-culprits 3 \\"
echo "    --confidence 0.75 \\"
echo "    v2.0 HEAD -- go test ./..."
echo ""
echo "  ./culprit-finder run"
echo ""

# Example 4: Interactive mode
echo "==================================================================="
echo "  Example 4: Interactive Configuration"
echo "==================================================================="
echo ""
echo "Let the tool guide you through configuration:"
echo ""
echo "  ./culprit-finder start -i main HEAD -- cargo test"
echo ""
echo "This will prompt you for:"
echo "  - Test flakiness level"
echo "  - Expected number of culprits"
echo ""

# Example 5: Large commit range
echo "==================================================================="
echo "  Example 5: Large Commit Range"
echo "==================================================================="
echo ""
echo "For searching through many commits:"
echo ""
echo "  ./culprit-finder start \\"
echo "    --max-culprits 2 \\"
echo "    --repetitions 5 \\"
echo "    --timeout 20m \\"
echo "    origin/main HEAD -- pytest tests/"
echo ""
echo "  # In another terminal, monitor progress:"
echo "  watch -n 5 ./culprit-finder status"
echo ""

# Example 6: Resuming interrupted search
echo "==================================================================="
echo "  Example 6: Interrupt and Resume"
echo "==================================================================="
echo ""
echo "Searches can be safely interrupted:"
echo ""
echo "  ./culprit-finder run"
echo "  # Press Ctrl+C to interrupt"
echo "  # Later, resume:"
echo "  ./culprit-finder run"
echo ""

# Example 7: Checking configuration
echo "==================================================================="
echo "  Example 7: Configuration Details"
echo "==================================================================="
echo ""
echo "View your session configuration:"
echo ""
echo "  ./culprit-finder config"
echo "  ./culprit-finder list --limit 10"
echo ""

# Example 8: Real-world workflow
echo "==================================================================="
echo "  Example 8: Complete Workflow"
echo "==================================================================="
echo ""
echo "Typical workflow for CI failure investigation:"
echo ""
echo "  # 1. Identify the failure point"
echo "  git log --oneline main..feature-branch"
echo ""
echo "  # 2. Start culprit finder"
echo "  ./culprit-finder start main feature-branch -- ./run-tests.sh"
echo ""
echo "  # 3. Run the search (can take time)"
echo "  ./culprit-finder run"
echo ""
echo "  # 4. Review results"
echo "  ./culprit-finder status -v"
echo ""
echo "  # 5. Investigate identified culprits"
echo "  git show <culprit-sha>"
echo "  git revert <culprit-sha>"
echo ""
echo "  # 6. Clean up"
echo "  ./culprit-finder reset"
echo ""

# Example 9: Performance optimization
echo "==================================================================="
echo "  Example 9: Optimizing for Speed vs Accuracy"
echo "==================================================================="
echo ""
echo "Fast mode (when tests are very stable):"
echo ""
echo "  ./culprit-finder start \\"
echo "    --max-culprits 1 \\"
echo "    --repetitions 1 \\"
echo "    main HEAD -- make quick-test"
echo ""
echo "Accurate mode (for production/CI):"
echo ""
echo "  ./culprit-finder start \\"
echo "    --max-culprits 2 \\"
echo "    --repetitions 7 \\"
echo "    --confidence 0.9 \\"
echo "    main HEAD -- make full-test"
echo ""

# Example 10: Troubleshooting
echo "==================================================================="
echo "  Example 10: Troubleshooting"
echo "==================================================================="
echo ""
echo "If no culprits found, try increasing repetitions:"
echo ""
echo "  ./culprit-finder reset"
echo "  ./culprit-finder start \\"
echo "    --repetitions 7 \\"
echo "    --flake-rate 0.2 \\"
echo "    main HEAD -- <test-command>"
echo "  ./culprit-finder run"
echo ""
echo "If too many ambiguous commits:"
echo ""
echo "  # Check test consistency"
echo "  for i in {1..10}; do make test && echo \"Pass\" || echo \"Fail\"; done"
echo ""
echo "  # Increase repetitions if flaky"
echo "  ./culprit-finder reset"
echo "  ./culprit-finder start --repetitions 10 ..."
echo ""

echo "==================================================================="
echo "  Quick Reference"
echo "==================================================================="
echo ""
echo "Commands:"
echo "  start   - Initialize a new search"
echo "  run     - Execute the search"
echo "  status  - Check progress and results"
echo "  config  - View configuration"
echo "  list    - Show commits in range"
echo "  reset   - Clean up session"
echo ""
echo "For detailed help:"
echo "  ./culprit-finder --help"
echo "  ./culprit-finder start --help"
echo "  ./culprit-finder run --help"
echo ""
echo "For more information, see README.md"
echo "==================================================================="
